name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      # Install Nix
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      # Install omnix (om)
      - name: Install om
        run: nix --accept-flake-config profile install github:juspay/omnix

      # Show available configs/packages
      - name: om show
        run: om show .

      # Run CI builds (allow unfree + impure mode)
      - name: om ci
        run: |
          export NIXPKGS_ALLOW_UNFREE=1
          om ci run --systems x86_64-linux -- --impure
